services:
#    social_pro.example:
#        class: SocialProBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  projects_controller:
        class: SocialProBundle\Controller\ProjectsController
        calls:
              - [setContainer, ["@service_container"]]